//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::group_chat::Entity as GroupChat;
pub use super::group_chat_member::Entity as GroupChatMember;
pub use super::group_chat_message::Entity as GroupChatMessage;
pub use super::private_message::Entity as PrivateMessage;
pub use super::profile::Entity as Profile;
